---
version: '3'

volumes:
  cowrie-log:

services:
  cowrie:
    image: cowrie/cowrie
    ports:
      - "2223:2222"
    volumes:
      - ./cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      - ./userdb.txt:/cowrie/cowrie-git/etc/userdb.txt
      - ./log/cowrie.json:/cowrie/cowrie-git/var/log/cowrie/cowrie.json
      - ./tty:/cowrie/cowrie-git/var/lib/cowrie/tty
      - ./downloads:/cowrie/cowrie-git/var/lib/cowrie/downloads/